project:
  type: manuscript
manuscript:
  code-links: binder
execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  elsevier-pdf:
    keep-tex: true  



